name:  Deployment for Strapi API

on:
  push:
    branches:
      - mahesh-branch


jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setting up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.MAHESHR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.MAHESH_AWS_SECRET_KEY_ID }}
          aws-region: us-west-2 
      - name: Setting up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.MAHESHR_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add SSH key to the agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.MAHESHR_PRIVATE_KEY }}     

      - name:  Setting up terraform
        uses: hashicorp/terraform-github-actions/init@v0.4.0
      - name: Initialization
        run: terraform init
        working-directory: ./Terraform
      - name: Apply the infrastructure
        run: terraform apply -var-file "dev.tfvars" -auto-approve
        working-directory: ./Terraform